version: "3"

services:
    mysql:
        image: "mysql:8.0.32"
        container_name: "mysql"
        environment:
            MYSQL_DATABASE: 'shadow'
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"

    web:
        build: .
        image: "snowflyaway/shadow:0.1"
        container_name: "shadow"
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - mysql



