version: "3.8"

services:
    mysql:
        image: "mysql:8.0.32"
        container_name: "mysql"
        environment:
            MYSQL_DATABASE: 'shadow'
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"

    web:
        build: .
        image: "snowflyaway/shadow:0.1"
        container_name: "shadow"
        environment:
            - "JAVA_OPTS=-Xms256m -Xmx256m"
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            mysql:
                condition: service_started
#                 condition: service_healthy
#                 condition: service_completed_success



