FROM openjdk:8-jre-alpine
WORKDIR /opt/app
RUN echo "Asia/Shanghai" > /etc/timezone
ADD ./shadow-*.jar /opt/app/app.jar
EXPOSE 8080

ENV JAVA_OPTS=""

ENTRYPOINT java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /opt/app/app.jar
