spring:
  application:
    name: shadow
  jpa:
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true

server:
  port: 8080
  # 配置Tomcat的访问日志格式化输出
  tomcat:
    accesslog:
      directory: /data/
      enabled: true
      # common - %h %l %u %t "%r" %s %b
      # combined - %h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"
      pattern: '%a - - %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
      prefix: access_trace_shadow
      rotate: false
