spring:
  application:
    name: shadow
  profiles:
    active: druid
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      continue-on-error: true

  #  elasticsearch:
  #    uris: ${ES_HOSTS:}
  #    username: ${ES_USERNAME:}
  #    password: ${ES_PASSWORD:}

  devtools:
    restart:
      enabled: true  #设置开启热部署

  thymeleaf:
    cache: false #使用Thymeleaf模板引擎，关闭缓存
    mode: HTML
    encoding: UTF-8

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  #  ehcache 缓存
  cache:
    type: ehcache
    ehcache:
      config: ehcache/ehcache.xml

logging:
  level:
    com.github.shadow.mapper: debug
    org.springframework: warn

server:
  port: 8080
  shutdown: graceful
  # 配置Tomcat的访问日志格式化输出
  #  tomcat:
  #    accesslog:
  #      directory: /data/
  #      enabled: true
  #      # common - %h %l %u %t "%r" %s %b
  #      # combined - %h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"
  #      pattern: '%a - - %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
  #      prefix: access_trace_shadow
  #      rotate: false
  undertow:
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    #buffers-per-region: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256
    accesslog:
      # 是否开启访问日志
      enabled: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.github.shadow.entity
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: auto
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty

knife4j:
  enable: true
  setting:
    enable-swagger-models: true
    swagger-model-name: 实体类列表
    enable-document-manage: true
    enable-after-script: true
    enable-host: false
    enable-host-text:
    enable-request-cache: true
    enable-filter-multipart-apis: false
    enable-filter-multipart-api-method-type: POST
    language: zh-CN
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2023 flankxu All Rights Reserved
    enable-debug: true
    enable-open-api: false
    enable-group: true
  cors: false
  production: false
  basic:
    enable: false
    username: admin
    password: admin
